# Generated by Django 3.2.10 on 2022-01-27 03:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('ticker', models.CharField(max_length=50, verbose_name='Ticker')),
                ('sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Ativo',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_name', models.CharField(max_length=5, verbose_name='Nome abreviado')),
            ],
            options={
                'verbose_name': 'Tipo de Ordem',
                'verbose_name_plural': 'Tipo de Ordens',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=datetime.datetime.now, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Carteira',
            },
        ),
        migrations.CreateModel(
            name='Wallet_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('invested_amount', models.FloatField(default=0, verbose_name='Total investido')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_wallet', to='wallets.asset', verbose_name='Ativo')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Carteira_Ativo',
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='asset',
            field=models.ManyToManyField(blank=True, through='wallets.Wallet_Asset', to='wallets.Asset', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Data')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.asset', verbose_name='Ativo')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.ordertype', verbose_name='Tipo de Ordem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ordem',
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.assettype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.assettype', verbose_name='Tipo'),
        ),
    ]
