# Generated by Django 3.2.10 on 2022-01-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
    ]
