# Generated by Django 3.2.10 on 2021-12-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20211227_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='category',
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.assettype', verbose_name='Parent Type'),
        ),
        migrations.DeleteModel(
            name='MajorCategory',
        ),
    ]
