# Generated by Django 3.2.10 on 2021-12-27 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0003_auto_20211227_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('invested_amount', models.FloatField(verbose_name='Invested Amount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.asset', verbose_name='Asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet', verbose_name='Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='asset',
            field=models.ManyToManyField(blank=True, through='wallets.Wallet_Asset', to='wallets.Asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
