# Generated by Django 3.2.10 on 2021-12-28 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0004_auto_20211227_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=5, verbose_name='Short Name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Date')),
                ('value', models.FloatField(verbose_name='Value')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.asset', verbose_name='Asset')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.ordertype', verbose_name='Ortder Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
