# Generated by Django 3.2.10 on 2022-01-27 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20220112_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='update_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='wallet_asset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_wallet', to='wallets.asset', verbose_name='Ativo'),
        ),
    ]
